### ISSUE TITLE
NAN uncurrency filtering only when currency is not mandatory?

### ISSUE THREAD

**Issue by leodido** [leodido/moneylaundry#11]
See this [fixme](https://github.com/leodido/moneylaundry/blob/develop/library/Filter/Uncurrency.php#L357).

If accepted as correct `"NaN"` will be filtered to `double(NAN)` only if currency symbol is set as not mandatory.

At the moment `"NaN"` is always filtered to `double(NAN)` in both situations (currency symbol mandatory or not mandatory.

Please feedback in pvt, @leogr.

**Comment by leogr** [comment]
NaN is a special case that may be enabled in lenient mode only, because NumberFormatter doesn't not handle the currency when try to format a `double(NAN)` and can not extract the currency when try to parse a `"NaN"` (the currency symbol is lost always).

For the same reason, it can not be accepted if currency symbol has been set as mandatory.

**Comment by leodido** [comment]
Ok, see #14.
